### ISSUE TITLE
Quit functionality is broken in Python 3

### ISSUE THREAD

**Issue by Lekensteyn** [pwr/Solaar#120]
When trying to quit Solaar through the systray, the window gets closed but the application is still active in the tray (although unresponsive). I do not get any errors with debugging enabled though.

Python3 has another oddity, when I move my mouse with Python 2, I get a lot of debugging messages saying that a notification was ignored. In python 3 this is not printed (not a bad thing though, solaar should not print debugging messages for every hidraw event).

**Comment by jrbenito** [comment]
@Lekensteyn 

Not reproducible. Let´s close this one?

**Comment by Lekensteyn** [comment]
Yay:)
