### ISSUE TITLE
About Solaar project

### ISSUE THREAD

**Issue by david-geiger** [pwr/Solaar#150]
For Author of the project:

What happens there with this project ? is it abandoned ?

because it has been a few months now that the project does not advance, and I find it very unfortunate given the value and effectiveness of Solaar software.

Regards david.david.

**Comment by jrbenito** [comment]
@Lekensteyn and @david-geiger 

No point in keep this open. Patches are always welcome.

let´s close this? Thanks.

**Comment by Lekensteyn** [comment]
Yep, contributions like the one from @jrbenito help a lot. Patches welcome! :-)
