### ISSUE TITLE
ability to run a script on device insertion

### ISSUE THREAD

**Issue by amias-channer** [pwr/Solaar#156]
Hello Solaarians,

thanks for this tool and thanks for being cool and sharing it , it really makes my mouse better :)

i had a look and couldn't find something like this in solaar already , apologies if i missed it.

I have a suggestion , i have a little shell script i run to map the buttons on my performance mouse , i run it on session start but rarely log out . What would be great would be if solaar could run arbitrary script when it notices my mouse is inserted.

my script does this : 

```
# try to find logitech mouse using xinput
XID=`xinput --list | grep PID:101a | cut -f2 -d'=' | cut -f1 -d'[' | cut -f1 -d' ' `
if [ "$XID" -eq "$XID" ] 2>/dev/null; then
    # its a number so we ...  
    echo "Found logitech mouse at : $XID"
    # set the 'zoom' button to be middle click for pasting
    xinput set-button-map $XID 1 13 3 4 5 6 7 8 9 10 11 12 2 14 15 16 17 18 19 20 21 22 23 24
else
    echo "Could not find a logitech mouse from this list"
    xinput --list
fi
```

at the moment i have to run it when i reconnect my mouse ( i take it home and leave my work computer suspended then plug it into my laptop ) but it would be really handy if solaar could allow me to attach a script to the device.

This would also allow people to implement a lot of other functionality for logitech devices without cluttering the gui or requiring more effort from you guys.

I'm not a C coder myself but i am software tester so i'm happy to help test changes.
I'm using ubuntu 13.10 and 14.04.

Cheers
Amias

**Comment by jrbenito** [comment]
@Lekensteyn 

another candidate to be closed.
