### ISSUE TITLE
Support fn-swap on K400 Touch.

### ISSUE THREAD

**Issue by cirosantilli** [pwr/Solaar#162]
Solaar 0.9.2 + Ubuntu 12.04 kernel 3.11.0 x86_64.

If I understand correctly, it is not currently supported: https://github.com/pwr/Solaar/blob/master/docs/devices.md If that is the case, feature request.

Input:

```
sudo solaar-cli config 1
```

Outputs a failure to read:

```
# Wireless Touch Keyboard K400

# Swap Fx function
#   possible values: on/true/t/yes/y/1 or off/false/f/no/n/0
# fn-swap = ? (failed to read from device)
```

Input:

```
sudo solaar-cli config 1 fn-swap
```

Output:

```
solaar-cli: error: failed to read 'fn-swap'
```

Input:

```
sudo solaar-cli config 1 fn-swap true
```

Output:

```
solaar-cli: error: failed to set 'fn-swap' = 'True' [True]
```

**Comment by eddie-dunn** [comment]
There are two revisions of this keyboard. Perhaps it doesn't work with the older revision? I have the old one, and get the same errors as OP.

**Comment by dstensnes** [comment]
I thought I had the same, but I noticed mine says: "K400 Plus", so then maybe it is 3 different keyboard variants called K400:
```
# ./ltunify -D info 1

wr: 10 ff 81 00 00 00 00
rd: 10 ff 81 00 00 00 00
Reporting Flags (Receiver) = 00
Wireless notifications     = no
Software Present           = no
wr: 10 ff 80 00 00 01 00
rd: 10 ff 80 00 00 00 00
Successfully enabled notifications
wr: 10 ff 83 b5 20 00 00
rd: 11 ff 83 b5 20 09 08 40 4d 04 02 01 47 00 00 00 00 00 00 00
wr: 10 01 00 14 00 00 00
rd: 10 01 8f 00 14 09 00
Failed to retrieve version: 0x09 (RESOURCE_ERROR)
wr: 10 ff 83 b5 30 00 00
rd: 11 ff 83 b5 30 d4 34 14 9f 1e 40 00 00 09 00 00 00 00 00 00
wr: 10 ff 83 b5 40 00 00
rd: 11 ff 83 b5 40 09 4b 34 30 30 20 50 6c 75 73 00 00 00 00 00
HID++ version: unknown
Device index 1
Keyboard
Name: K400 Plus
Wireless Product ID: 404D
Serial number: D434149F
Device was unavailable, version information not available.
wr: 10 ff 80 00 00 00 00
rd: 10 ff 80 00 00 00 00
Successfully disabled notifications

wr: 10 ff 81 00 00 00 00
rd: 10 ff 81 00 00 00 00
Reporting Flags (Receiver) = 00
Wireless notifications     = no
Software Present           = no
#
```

**Comment by jrbenito** [comment]
Hi @cirosantilli , @jhmegorei , @eddie-dunn , @dstensnes ,

I know that K400 plus is supported on master branch (get latest) version as per #308 and #310. 

Also, #289 and #290 relates to K400 (I believe same device reported here). @verybadsoldier report that there is FN-Swap for the K400.

Could you please try latest commit on master branch on your devices? It would be good to get a `solaar show` output from all of you so we can comparte the k400 revisions and if necessary workout a solution for everyone.

If it works on latest master for everyone, let´s close this issue.

Thanks.

**Comment by chrisl8** [comment]
FYI: I am using Ubuntu 16.04. I have a Logitech K400 Plus which I bought about a month ago.
The version of Solaar that I got by running `sudo apt install solaar` did NOT allow me to swap the function keys.

Using the current master branch version from github *DOES* allow me to swap the function keys.

Specifically:
```
sudo apt-get install devscripts
git clone https://github.com/pwr/Solaar.git
cd Solaar/packaging/
./build_deb.sh
cd ../dist/
sudo dpkg -i ./solaar_0.9.2-2_all.deb
```
Reboot and then it works great.

Let me know if there is any other information or output that I can provide to help you close this issue.

**Comment by arborrow** [comment]
I am running Ubuntu 16.10 and had installed solaar via apt install solaar and there was no option for the FN-Swap. I found this post and cloned the project and ran solaar from the command line and connected to my device and there was an option for the FN-Swap - horray! Many thanks! Peace - Anthony

**Comment by Lekensteyn** [comment]
Thanks @arborrow for confirming!

**Comment by odedniv** [comment]
Had this problem as well, using master fixed it.
Looks like there haven't been a lot of releases lately, why not tag? :smile:

**Comment by jrbenito** [comment]
@odedniv ,

Daniel (@pwr) seems to be busy lately and Peter (@Lekensteyn)  is  caring this project on his spare time. They both have access to this repo but only Daniel has access to Ubunto PPA. Peter plans to release soon.

**Comment by Lekensteyn** [comment]
@odedniv @jrbenito I have indeed been busy, trying to catch up with the flood. Still need to do some testing before rolling a tag (one possible blocker issue is that the tray icon was not working on Plasma and possibly other environments). Assistance in triaging the issues/testing is welcome :-)

Thanks @jrbenito for checking the issues and sorry for the delay from my side.

**Comment by odedniv** [comment]
I have that issue (on plasma)! Will see what i can do.

**Comment by edsko** [comment]
For people stumbling across this issue, `master` also worked for me but running it without arguments didn't bring up a GUI window (nothing seemed to happen although probably something did somewhere :). But on the command line this works:

```
solaar config 1 fn-swap False
```

Now the function keys have their "regular" function (I did find it needed to toggle it a few times for some reason though).

**Comment by edsko** [comment]
Actually, it's worse than "a few times". It seems to revert back to "True" after a while..?

**Comment by elstoc** [comment]
I get the same with the latest version. Solaar successfully swaps the function key usage then after ten minutes or so it automatically swaps back.

**Comment by parkerlreed** [comment]
This isn't showing up at all for me on latest git

The features shows in the device info but there is no option to toggle in the UI.

````
  3: Wireless Touch Keyboard K400
     Codename     : K400
     Kind         : keyboard
     Wireless PID : 4024
     Protocol     : HID++ 2.0
     Polling rate : 8 ms (125Hz)
     Serial number: 20AF489D
          Firmware: RQK 50.01.B0013
     The power switch is located on the edge of top right corner.
     Supports 22 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: FEATURE INFO           {0002}   
         3: DEVICE FW VERSION      {0003}   
         4: DEVICE NAME            {0005}   
         5: BATTERY STATUS         {1000}   
         6: REPROG CONTROLS        {1B00}   
         7: REPROG CONTROLS V3     {1B03}   
         8: WIRELESS DEVICE STATUS {1D4B}   
         9: unknown:1DF0           {1DF0}   hidden
        10: unknown:1DF3           {1DF3}   internal, hidden
        11: unknown:1E00           {1E00}   hidden
        12: VERTICAL SCROLLING     {2100}   
        13: HI RES SCROLLING       {2120}   
        14: MOUSE POINTER          {2200}   
        15: FN INVERSION           {40A0}   
        16: NEW FN INVERSION       {40A2}   
        17: ENCRYPTION             {4100}   
        18: KEYBOARD LAYOUT        {4520}   
        19: TOUCHPAD FW ITEMS      {6010}   
        20: TOUCHPAD SW ITEMS      {6011}   
        21: TOUCHPAD WIN8 FW ITEMS {6012}   
````
