### ISSUE TITLE
Mouse loses ability to click

### ISSUE THREAD

**Issue by ntzrmtthihu777** [pwr/Solaar#163]
Not sure where this issue arrises, but every now and again my mouse (Wireless Trackball M570 [M570:ADC9A18D]) loses the ability to click; Note, I can still move it about, and sometimes I can click about inside of text fields, but in general it becomes useless.

The only workaround I know of for this issue is to switch to a tty and back to the xserver; this problem has arose with both the gnome-desktop and xfce4, distro arch linux.

**Comment by Lekensteyn** [comment]
Is this still reproducible? Solaar should not cause this unless something is wrong.

**Comment by jrbenito** [comment]
@Lekensteyn 

I could not observe this and agree that Solaar does not look guilt. Let´s close this?
