### ISSUE TITLE
Incorrect path in tools/po-update.sh on openSUSE

### ISSUE THREAD

**Issue by micrococo** [pwr/Solaar#166]
Hi.

/usr/share/locale-langpack/$LL_CC/LC_MESSAGES/$1.mo should be /usr/share/locale-bundle/$LL_CC/LC_MESSAGES/$1.mo on openSUSE. Maybe you could check if the system is openSUSE in the script.

Greetings.

**Comment by jrbenito** [comment]
@micrococo ,

Still a valid issue?

**Comment by jrbenito** [comment]
@Lekensteyn ,

This is another that can be closed.
