### ISSUE TITLE
Performance MX mouse is not recognized

### ISSUE THREAD

**Issue by jtliii** [pwr/Solaar#169]
I have a brand new Performance MX mouse and a fresh install of Mint 17, the keyboard works fine but the mouse isn't recognized. According to the compatibility list the Performance MX mouse is supported and I know the mouse works because this is a dual boot system with Windows and the the mouse works fine in Windows. Does Solaar simply add functionality to an already detected mouse or will it detect the mouse for Mint. I have tried Ubuntu, Mint 16 and Mint 17 and the mouse doesn't work in any.

Thanks for your help.

**Comment by jrbenito** [comment]
@Lekensteyn 

While this is weird, long time has passed. Are we going to look into this or just close and revisit if this happens again?

**Comment by Lekensteyn** [comment]
Let's close it, I doubt that more progress is made unless somebody starts putting some time into investigating this.

Summary (from what I gathered):
Problem: A receiver with the keyboard paired fails to pair (connect) the Performance MX mouse.
Workaround: pair the mouse first, then the keyboard.

If people have more ideas, feel free to comment/re-open.
