### ISSUE TITLE
Here's An Interesting One...

### ISSUE THREAD

**Issue by drhardison** [pwr/Solaar#186]
Dear Daniel,
First let me thank you for creating such a wonderful tool.
I have an interesting problem I have a Logitech Keyboard MK700/MK710 and I can successfully pair it with Solaar and see that it has a full battery and that the connection is indeed encrypted as it should be.
When it hasn't been in use and I hit a few keys it renews the connection with Solaar, so my computer seems to be getting some sort of signal from it, but whenever I try to type something, it doesn't yield any results.
I have a Microsoft Keyboard that works with Linux, so I'm not in desperate need for a solution, but I would be nice to have my expensive keyboard working again, and I thought, if you're anything like me, this problem might intrigue you if you don't already have a solution for it.

Thanks,
Joe

**Comment by jrbenito** [comment]
@Lekensteyn 

Long time has passed and I believe this could be related with USB/HID Kernel drivers not with Solaar. Since no one is complaining about, can we close this one?

thanks
