### ISSUE TITLE
Can't unpair old device / pair new device MX1100 receiver / M-RCR147 (MX1100) mouse [046d:c526]

### ISSUE THREAD

**Issue by MagicFab** [pwr/Solaar#189]
After getting a replacement receiver for a combo keyboard/mouse MX1100, the new receiver is recognized by Solaar but can't unpair the old device or pair the new one (buttons greyed out).

I am running Solaar 0.9.2 in Debian 7.

Receiver:
Path         : /dev/hidraw1
USB id       : 046d:c526
Serial       : A11B81B4
  Firmware   : 05.00.B0023
Notifications: wireless

Mouse:
Index        : 1
Wireless PID : 100C
Protocol     : unknown
Serial       : A11B81B4

**Comment by jrbenito** [comment]
@MagicFab 

Are you able to provide information about receiver? (lsusb)

thanks

**Comment by jrbenito** [comment]
This receiver is supported on latest master branch.

@MagicFab  or @Lekensteyn 

Could you please close this ticket?

Thanks.

**Comment by Lekensteyn** [comment]
There was another ticket about an issue with a receiver with a single receiver, but I forgot which.

If the problem persists, please re-open/comment. Thanks!

**Comment by MagicFab** [comment]
OK to close, I don't have access to this hardware anymore.
