### ISSUE TITLE
Error when calling "solaar"

### ISSUE THREAD

**Issue by eduards** [pwr/Solaar#190]
got the following error after "solaar" command in the terminal:

Traceback (most recent call last):
  File "/usr/bin/solaar", line 43, in <module>
    import solaar.gtk
  File "/usr/share/solaar/lib/solaar/gtk.py", line 25, in <module>
    import solaar.i18n as _i18n
  File "/usr/share/solaar/lib/solaar/i18n.py", line 47, in <module>
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

I used the solaar-cli tool instead. 
My OS: Distributor ID: Linux Mint 17 Qiana

**Comment by jrbenito** [comment]
@eduards ,

Are you able to try again with latest master branch commit?

thanks.

**Comment by Lekensteyn** [comment]
Hopefully it is an intermittent problem, if not, please re-open. Thanks!

**Comment by pfps** [comment]
This does not appear to be a Solaar problem.

See https://stackoverflow.com/questions/14547631/python-locale-error-unsupported-locale-setting/14548156 for more information.
