### ISSUE TITLE
Theres anyway to compile for ARMv6 ?

### ISSUE THREAD

**Issue by katzzero** [pwr/Solaar#195]
First of all, congrats for the good work! :)
I´m new to programing and i tried to compile for armv6 (raspbian-raspberry pi) with no luck.
i need to use a MK270 combo in it but it looses the keyboard and mouse all the time and need to reset.
i use it only in terminal and i dont need the graphic, only the CLI.
Can anyone show me a way to do it ? if its possible.
Thanks in advance !

**Comment by Lekensteyn** [comment]
Solaar does not really need to be compiled. If your USB device periodically gets in an unusable state, check the power supply and `dmesg` for any hints. I have successfully used the Logitech Unifying receiver in a Raspberry Pi, but that was the only device (no Wi-Fi stick was connected simultaneously).

**Comment by katzzero** [comment]
I will try that and post here the results. Thanks for the answer ! theres
any way to refresh it without a restart ?
Thanks !!

2015-01-02 7:58 GMT-02:00 Peter Wu <notifications@github.com>:

**Comment by Lekensteyn** [comment]
Try unplugging/inserting the USB receiver. If that causes a power surge which resets the pi, try to unload/load the USB module (if the driver is loaded as module).

**Comment by katzzero** [comment]
I found that java was crashing the driver module. updated java to sdk 8 and
everything is working again. anyway it dont make any sense to me. Thanks
for the help and sorry for the trouble !


2015-01-03 13:03 GMT-02:00 Peter Wu <notifications@github.com>:

**Comment by Lekensteyn** [comment]
Huh, Java? Sounds odd, but as the problem is gone: /close
