### ISSUE TITLE
No Logitech adapter found

### ISSUE THREAD

**Issue by dmaglio** [pwr/Solaar#196]
My logitech combo mouse + keyboard is incompatible?
Bus 002 Device 004: ID 046d:c505 Logitech, Inc. Cordless Mouse+Keyboard Receiver

**Comment by jrbenito** [comment]
Is this a Nano receiver? (non unifying?) 

I have this:
```
$ lsusb -d 046d:
Bus 005 Device 004: ID 046d:c534 Logitech, Inc. Unifying Receiver
Bus 005 Device 005: ID 046d:c52b Logitech, Inc. Unifying Receiver
```

But the first one is not recognized (and actually isn't a true unifying but maybe a Unifying ready?)

**Comment by jrbenito** [comment]
@dmaglio ,

Could you please provide more information on this receiver and mouse/keyboard its support? Are you able to try modifications similar to what I describe in #234 and post information?

**Comment by jrbenito** [comment]
@Lekensteyn ,

No answer, no access to a receiver with PID `c505`, no mention what mouse/keyboard this receiver comes with. 

Let´s close this one?
