### ISSUE TITLE
Keyboard status

### ISSUE THREAD

**Issue by krassswr** [pwr/Solaar#198]
I have keyboard K750 and it works like a charm. But this model don't have LED status indicators. So it will be nice to know when Num, CAPS and Scroll Lock are pressed. I use xfce4.1 on debian testing and I didn't find working solution to show status of keyboard.

**Comment by marcusrugger** [comment]
I'd like to second this feature request.

**Comment by jtsagata** [comment]
There is applets to do that

**Comment by krassswr** [comment]
I found "Kbdleds" plugin. But it was in RPM package and i have to convert it do deb with Alien. Because in current version of Debian testing can't be compiled. Anyway it works now.

**Comment by jrbenito** [comment]
@krassswr and @Lekensteyn ,

Not in solaar scope, could you please close this?

Thanks
