### ISSUE TITLE
Solaar gui broken

### ISSUE THREAD

**Issue by canteo** [pwr/Solaar#199]
Hi,

I have two keyboards: K400, K270 and one mouse M235. They all work fine with Solaar, but for some reason something funny happened to the GUI.
I have paired them with my Ubuntu 14.10 and in the GUI, when i select the top level tree option in the left "Unifying receiver", the panel in the right does not get refreshed, and so, the option for "Pair new device" is gone...
I suspect a problem with Python version (i have Python 2.7.8)... When i run the solaar GUI through the command line, there are two errors about Python not expecting some "None" value in a method. They are below.

$ solaar
Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/ui/window.py", line 387, in _device_selected
    _update_info_panel(device, full=True)
  File "/usr/share/solaar/lib/solaar/ui/window.py", line 692, in _update_info_panel
    _info._icon.set_from_icon_name(icon_name, _DEVICE_ICON_SIZE)
TypeError: Argument 1 does not allow None as a value

It would be nice if you can have a look at this, as the tool is very good!

Thank you.

**Comment by Lekensteyn** [comment]
Please try the referenced patch, it was made a few months ago but still seems to work.

**Comment by tian2992** [comment]
Merged patch manually, Did not work for me. Did not display a window at all. Running on KDE.

**Comment by tian2992** [comment]
Worked,  my reciever was not working properly.

**Comment by Lekensteyn** [comment]
Great, thanks for confirming!
