### ISSUE TITLE
The Unifying devices and limit of forty-five (45) unique connections

### ISSUE THREAD

**Issue by 3F** [pwr/Solaar#205]
_... maybe you know, because your software worked with Unifying receivers and you can know more about protocol and inner structure, similar problem etc._

So, needed a more information about wonderful limitation for all Logitech Unifying products.

I think it's the best restriction for all my practice :) 
why ? who ? for what ? this is the first thoughts when you see the official notice after locked devices - "Some Unifying devices have a limit of forty-five (**45**) unique connections" (link on official site is no more available and the new i can't find, but you can also see the [similar problem](http://forums.logitech.com/t5/Keyboards-and-Keyboard-Mice/Unifying-receiver-45-connection-limit/m-p/824117))

yeah, great news

so, I got a similar problem in past year and I tried to contact with official supports 3 times i remember. However, no any informations... full ignoring. Great news for new purchased product :) and moreover, i'm afraid for my others the Unifying devices... 

incredibly for standard operations with official software o_o All my receivers not kept last pairing with this keyboard, i.e. i can't use this keyboard anymore

"in the trash.. later" - I thought, and ~year later, today i agian see this my new old locked keyboard K520

End of long history :) **to the question**:

In general, lock should be exist on devices, not for receivers. How it's stored and where this stored ? EEPROM ? maybe it's not a hard lock for programmatically changing

Can we manually set key for receiver for pairing this device ? or problems with certificate or some crc ?

**Comment by Lekensteyn** [comment]
I am afraid that you will not be able to circumvent this issue, otherwise Logitech would have released a software/firmware update to fix this. It is not good for their PR to have such issues.

**Comment by 3F** [comment]
> I am afraid that you will not be able to circumvent this issue

well :( as is.. no time for own analysis

for all - **be careful with all** the Unifying devices from Logitech! who would have thought at all about this -_- *official support is silent*

anyway, would be nice to get a more information about this restriction if anyone knows or have a more time for debugging of used protocol etc... write here, i'm watching this

**Comment by Lekensteyn** [comment]
For clarity, the 45 connections limit occurs only with **some older devices**. See http://support.logitech.com/en_us/article/14577. My devices have no issues with this limit.

Without further details I can only speculate what happens. Perhaps the memory can only be rewritten X times.

**Comment by 3F** [comment]
> only with some older devices

maybe, I don't know..
but I also have the older Performance MX mouse (bought in ~2011) and many successful connections between 2-3 receivers before this case o_O

> You have two Unifying receivers: one on your laptop and one on your desktop. You use the same mouse with your laptop and desktop, and switch back and forth between the two Unifying receivers. Because your mouse is switching between two Unifying receivers, each time you connect, you use one of the total available connections. Eventually, you will hit the connection limit.

anyway [item above](http://support.logitech.com/en_us/article/14577) - awesome.


> Perhaps the memory can only be rewritten X times

:) yeah
but the EEPROM(for example - i.e. haven't seen scheme) not too expensive to use as complete solution for all logitech devices
and this.. *from tens or hundreds of thousands of times to a million re/write operations*

I mean yes, it can be hardware limitation with very very poor elements... but o_o
It seems more likely:

* incorrect some crazy additional protection over AES :)) e.g. only for keyboards devices etc. o_o
* or crazy-marketing, promotion and similar..


> http://support.logitech.com/en_us/article/14577
>> The device will continue to work with the last receiver it was connected to.

it will be nice :) but...

**Comment by Lekensteyn** [comment]
What is the error anyway? AFAIK there is no error, you just get a timeout right?

**Comment by 3F** [comment]
@Lekensteyn 

yes, immediately(2-4 sec) dropped the pairing as a 'device timout' for Solaar:

     WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: pairing error 1: device timeout

-

	22:34:06,669     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw1,6)>: pairing lock is open
	22:34:06,669     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,6)>: present, 1 paired device. (1) pairing lock is open
	22:34:06,709    ERROR [MainThread] solaar.ui.notify: showing <Notification object at 0xa266c84 (NotifyNotification at 0xa29d260)>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/notify.py", line 136, in show
	    n.show()
	  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
	    return info.invoke(*args, **kwargs)
	GError: The connection is closed
	22:34:10,588     INFO [ReceiverListener:hidraw1] logitech_receiver.notifications: <UnifyingReceiver(/dev/hidraw1,6)>: pairing lock is closed
	22:34:10,588  WARNING [ReceiverListener:hidraw1] logitech_receiver.notifications: pairing error 1: device timeout
	22:34:10,588     INFO [ReceiverListener:hidraw1] solaar.listener: status_changed <UnifyingReceiver(/dev/hidraw1,6)>: present, 1 paired device. (1) pairing lock is closed
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/__init__.py", line 165, in _status_changed
	    window.update(device, need_popup)
	  File "/usr/local/lib/python2.7/dist-packages/solaar/ui/window.py", line 780, in update
	    _model.set_value(item, _COLUMN.STATUS_ICON, 'network-wireless' if is_pairing else None)
	  File "/usr/lib/python2.7/dist-packages/gi/overrides/Gtk.py", line 1237, in set_value
	    Gtk.TreeStore.set_value(self, treeiter, column, value)
	  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
	    return info.invoke(*args, **kwargs)

this receiver already paired M310 and I think it was the last as 'the last receiver it was connected to' i.e. I don't remember

and similar with official utility

**Comment by Lekensteyn** [comment]
Since the protocol does not give any hint, there is nothing we can do (in the context of Solaar).

If you are tinkerer you could lookup FCC documents and see whether you can do something with the hardware inside. You said that you have already tried (customer) support, but if that does not work you have little options. Maybe you could get a radio spectrum analyzer and play with it, but that is all more advanced stuff.

**Comment by 3F** [comment]
> you can do something with the hardware inside

in the trash would be cheaper :) *it's not worth the trouble..* in general, I software developer

> You said that you have already tried (customer) support

yes, I have official ticket number of my issue on support.logitech.com
btw, currently I can't access to my account :) (*Error: No account found with that email address.*)

> Maybe you could get a radio spectrum analyzer and play with it

I think easier to use the EPROM-Programmer or similar for used type memory and similar keyboard to dump this :)

**Comment by SlySven** [comment]
It sounds like the Logitech coders had a thought originally along the lines of *"oh, lets let the device keep track of the connection history (which receiver it was paired with)"* and arranged for that data to be written to permanent memory and forgot to use a ring-buffer type arrangement rather than a straight list in that memory. 

This worked fine for the first few dozen times of testing and the design was signed-off for manufacturing for the earlier devices - but, as they only left space for 45 changes, it breaks on those earlier ones when that limit is reached - so someone spotted it and put out a fix for later models.  I'd say you'd have a claim for "product not suitable for intended purposes" in the UK (where I am) but the legislation in your part of the :earth_africa:  may be different.

**Comment by jrbenito** [comment]
@Lekensteyn 

Still relevant?

**Comment by Lekensteyn** [comment]
Barring new breakthroughs in reverse engineering, I doubt this will be possible and it will probably be out of scope for Solaar.

Enthusiasts with some time are free to comment here thoughj.

**Comment by dlenski** [comment]
The Logitech document on this issue is now [here](https://support.logi.com/hc/en-us/articles/360023187214).

I am wondering if this limit applies to a K750 keyboard purchased in ~2015…? It appears I can no longer re-pair it.

**Comment by pfps** [comment]
Possibly.   My understanding is that some devices use write-once memory and so can only pair a limited number of times.  

Although I don't have documentation on it, I expect devices with feature     REMAINING_PAIRING=0x1DF0 only pair a limited number of times.

But it also might be that you receiver is out of pairings.   Solaar keeps track of this, so click on the receiver in the main window.

**Comment by 3F** [comment]
> The Logitech document on this issue is now here.
>> The device **will** continue to work with the last receiver it was connected to.

The truth is that it's not a true. 'should' instead of 'will' is a correct word. Tested with my all 3 or 4 receivers to be sure (in that period).

>> You have two Unifying receivers: one on your laptop and one on your desktop. You use the same mouse with your laptop and desktop, and switch back and forth between the two Unifying receivers. Because your mouse is switching between two Unifying receivers, each time you connect, you use one of the total available connections. Eventually, you will hit the connection limit.

Yep, this was my case as I remember it. Between my two laptops with their two receivers.

>> If you're unable to connect your device to another Unifying receiver, please contact Customer Care.

Hmm, My account was simply deleted in attempts to contact them, 2015.

@dlenski, convey my greetings to them if you will try to contact!

2020, I don't remember where I placed my keyboard, probably, with other instruments for future soldering etc. But I did not have time/tools to inspect this or check something. More like this just a trash and nothing more.

![Logitech-Unifying-45-limit-K520](https://user-images.githubusercontent.com/3246589/98832545-00899e00-244e-11eb-8ee5-dfc0b9fb1b71.jpg)
*( my device, old photo from 2016 )*


@pfps

>  My understanding is that some devices use write-once memory and so can only pair a limited number of times.

My thoughts were about some configurable write protection comparing to HW/eeprom limitation. And according to [some publicly available datasheet](https://infocenter.nordicsemi.com/pdf/nRF24LE1_PS_v1.6.pdf) at 2020, this is it;

[![nRF24LE1H](https://user-images.githubusercontent.com/3246589/98832786-49d9ed80-244e-11eb-9a67-28069e8bc17b.png)](https://infocenter.nordicsemi.com/pdf/nRF24LE1_PS_v1.6.pdf)
*( Credits to Nordic products, using public datasheet from infocenter\.nordicsemi\.com )*

Memory:

* Program memory: 16 kB of Flash memory with security features (up to 1k erase/ write cycles)
* Data memory: 1 kB of on-chip RAM memory
* Non-volatile data memory: 1 kB 
* Non-volatile data memory extended endurance: 512 bytes (up to 20k erase/ write cycles)


16 kB code memory:

* 1k NV data memory
* Page size 512 bytes for NV data memory and program memory
* Two pages of 256 bytes each for extended endurance memory 
* 32 pages of main block + 1 InfoPage
* Endurance minimum 1000 write/erase cycles
* Extended endurance memory, minimum 20000 write/erase cycles
* Direct SPI programmable
* Configurable MCU write protection
* Readback protection

As we can see, IP area (512 bytes for configuration) can be configured and used in different ways.

The *X Logitech counter* could be stored in 256 bytes at 0x100 with protection or IP may also split the main block into protected and unprotected areas by using RDISMB (readback protection 1 byte size at 0x23 in IP). This can only be changed once by SPI command RDISMB (0x85) but can be reseted by ERASE ALL (0x62). This, however, will erase the entire IP (or only the main block if FSR.INFEN is low)

Anyway, there's no HW limitation around 24LE1(H); only Logitech bad design in their old products (REV.008 etc)

**Comment by W1Real** [comment]
My Nano adapter did throw the error: 

_"Lifespan exhausted receiver cannot be used to pair to a new device as it has reached its erase write cycles limit. Connect a new receiver to continue"_


I did just swap between my K345 and a K235 with one of their Dongles (They show up the same in Logi Bolt, they also look the same physically).

Then, suddenly one day, I get that error message. It's still paired with the last used keyboard (K235) but it didn't want to pair again with my K345.

I just ended up getting the other adapter from one of them and connected it so I could use my K345.

From now on, if I swap the keyboards I'll swap their respective dongles. I did even put a white tape on it and wrote which device it's paired so I won't forget.

BLATANT PLANNED OBSOLESCE. There are NO WARNINGS anywhere in the manuals or in Logitech's software or website. I never in my life would have thought a dongle would have limited writes that a regular user could reach.

![Capture](https://github.com/user-attachments/assets/817cf47a-241c-4024-a9e4-658f813b2169)


![image](https://github.com/user-attachments/assets/ca8c05b3-1552-42c6-9b34-3a59caa34578)

**Comment by dlenski** [comment]
> I'm sorry for my ranting. But this is beyond absurd user/consumer experience. I'd rather be told that it can pair only to one device forever than being sold that I can re-pair without consequences.

I agree.

> BLATANT PLANNED OBSOLESCE. There are NO WARNINGS anywhere in the manuals or in Logitech's software or website. I never in my life would have thought a dongle would have limited writes that a regular user could reach.

I _don't_ think this is/was intentional planned obsolescence however.

I think that Logitech never imagined users would attempt to move devices between Unifying Receivers frequently ***because it's such a PITA to do it with their official software***; seriously, it's so painful to do on Windows that I just take the dongle over to a Linux computer and do `solaar pair` from there, and on Mac it seems close to impossible.

Since it's _much easier_ to do this re-pairing with Solaar, I think it's basically only us who've done it enough to run into these issues. It appears that Logitech hadn't really expected this usage, and have barely acknowledged the problem, but (to their credit) they have [fixed the firmware in newer devices so that it doesn't have this limit](https://github.com/pwr-Solaar/Solaar/issues/205#issuecomment-89820963).
