### ISSUE TITLE
Arm v7 Suport.

### ISSUE THREAD

**Issue by katzzero** [pwr/Solaar#209]
Would be too hard to make it Arm v7 or better compatible ?
I use Lubuntu on an Odroid-c1 and it will be very useful to me ...
Thanks for the attention. :)

**Comment by Lekensteyn** [comment]
Have you tried installing it? This is all Python with no native code so it should work on any Linux platform ;)

**Comment by katzzero** [comment]
I tried once and it not worked ... but i installed again now and it asked
for python-pyudev ... after that it worked !
Sorry for bother ..
Thanks and Congratz for the excelent work !!


2015-03-30 7:01 GMT-03:00 Peter Wu <notifications@github.com>:
