### ISSUE TITLE
M570 trackball suport.

### ISSUE THREAD

**Issue by katzzero** [pwr/Solaar#211]
Hi !
I can´t pair my m570 trackball with my odroid running lubuntu.
It it supported ?

**Comment by Lekensteyn** [comment]
See #209, Solaar uses Python which is also supported by your ARM device.

**Comment by katzzero** [comment]
I know Solaar work on my device ... I cant use it with my m570 ... Works
fine with my mk220 ... But OK .. Close it ...thanks anyway ...
Em 12/04/2015 11:03, "Peter Wu" <notifications@github.com> escreveu:
