### ISSUE TITLE
Natural scrolling with touchpads

### ISSUE THREAD

**Issue by decibyte** [pwr/Solaar#215]
I've got a T650 I'm using with a laptop PC running Ubuntu. I've enabled Natural Scrolling (i.e "reversed") in the Mouse & Touchpad System Settings. This works for the built-in touchpad on the laptop, but not for the T650.

Similarly, I have a K830 I'm using with a desktop PC. With that, the Natural Scrolling option is not even available from the Mouse & Touchpad settings.

Is there a way to tell the underlying system that this device is(/has) a touchpad, from which input should be treated as such and allow/enable natural scrolling?

I've tried setting `kind=_DK.touchpad` for the T650, but that didn't have any effect.

If someone can point in the right direction, I will probably be able to implement this myself.

**Comment by decibyte** [comment]
With Ubuntu 15.04, released yesterday, this seems to be working. Thus my own itch has been scratched :)

I'll close this issue for now, but feel free to reopen if there's a way to make it work with older Linuxes.

**Comment by nickurak** [comment]
Did that help with your k830 as well?

**Comment by decibyte** [comment]
@nickurak I haven't tried yet. Let me get back to you when I've had the change.

**Comment by rahidelvi** [comment]
The issue appears again with the 3.19.0-25-generic kernel on Ubuntu 15.04 . Both the T650 and TK820 trackpads don't recognize natural scrolling. The scroll axis can be [tinkered with and adjusted][1], however, it would be nice to control this in solaar.

[1]: Eg. http://askubuntu.com/q/542073/60869
