### ISSUE TITLE
e930C hasn't been supported yet?

### ISSUE THREAD

**Issue by jiapei100** [pwr/Solaar#217]
Hi,

I'm using a Logitech e930C, and I didn't find it available by using Solaar.
The device is 046d:0843

Bus 002 Device 007: ID 046d:0843 Logitech, Inc. 

Can you please help to add e930C at your convenience?

Cheers
Pei

**Comment by jiapei100** [comment]
Checked... 
Even C920 is not able to be detected.
Solaar hangs with "No Logitech receiver found"

Suggestions?

Cheers
Pei

**Comment by Lekensteyn** [comment]
The [C930e][1] is a webcam just like the [C920][2]. These have no *wireless* Unifying receiver right? What functionality are you looking for? These devices are typically supported by video4linux drivers.

 [1]: http://support.logitech.com/product/webcam-c930e-business
 [2]: http://support.logitech.com/product/hd-pro-webcam-c920

**Comment by jrbenito** [comment]
@Lekensteyn ,

Let´s close this one? A lot time has passed and clearly Solaar will not find receivers on USB webcams.
