### ISSUE TITLE
Logitech M560 support

### ISSUE THREAD

**Issue by mhalano** [pwr/Solaar#226]
Linux kernel 4.2 come with Logitech M560 support. This mouse is a Windows mouse which sends mouse and keyboards signals. May be will be a good idea support the configuration of the shortcuts buttons?

**Comment by CzBiX** [comment]
`xbindkeys` (has a gui tool `xbindkeys-config`) is good enough to use.

**Comment by mhalano** [comment]
Yes, for experts maybe, but for beginners is not so adequate. Solaar could be very good to define options (like DPI selection, shortcuts) related to Logitech devices.

**Comment by hobarrera** [comment]
Configuring custom actions sounds a bit like feature creep, and out of scope. Something simple like sxhd (or, xbindkeys, if you prefer) should be enough. The documentation is quite clear (especially the former). 

If you need a GUI for that, you're better of asking for a gui-for-sxhkd than trying to get unrelated features into Solaar, IMHO.

**Comment by jrbenito** [comment]
@mhalano ,

Does solaar at least shows information about M560? DPI and other device settings is solaar responsibility, however, shortcut buttons are better handled by xbindkeys or similar.

Could you please post output of `solaar show`? If possible using latest master commit.

thanks.

**Comment by mhalano** [comment]
[solaar-show.txt](https://github.com/pwr/Solaar/files/615169/solaar-show.txt)

@jrbenito 

I cloned the git repository and used the <source dir>/bin/solaar command.

The result of command 'solaar show 1' (to only show mouse) is attached to this issue.

There is a new option in GUI to set smooth scrolling (I really don't know why since is defined by a hardware button only), but not option to set DPI.

Please, let me know if you need more help.

**Comment by jrbenito** [comment]
@mhalano,

Does this device support DPI setting? I could not find reference about this. Based on information you posted above, the device does support "smooth scroll" setting (`20: HI RES SCROLLING       {2120}`) but there is no option regarding DPI. Based on current Solaar implementation adjustable DPI setting should be listed by a HID++ 2.0 device as feature `{2201}`; notice that it does not list this for M560 on `solaar show` output.  **If it does support DPI setting**, I don´t know how it is set by Logitech software, and you will need to get a USB Pcap from USB receiver/SW conversation so we can investigate deeper.

Regarding reprogrammable buttons, now they are better handled by xbindkeys or similar input management software. Solaar is not yet prepared to this for any device and there is no plan for this anytime soon. If I understood right the can be reprogrammable to send custom key codes and I read on another issue here that @Lekensteyn  and @pwr  had no success while trying to reprogram them.

I submitted PR #317 with your contributed M560 information. Thanks!

BRs,
Benito

**Comment by Lekensteyn** [comment]
The devices cannot be changed to trigger different key events via the HID++ protocol. The features that name reprogrammable keys only provides hints to the software such that it can suggest buttons to be changed. At the moment that seems quite some work and it would be more preferable if there is a generic solution for all devices (so, not implementing it in Solaar).

**Comment by jrbenito** [comment]
@Lekensteyn and @mhalano ,

If there is no DPI change support on M560 device as it seems to be the case, we can close this issue since no button reprogramming will be done in Solaar.

Agree?

**Comment by Lekensteyn** [comment]
Does the device advertise adjustable DPI settings (product page?).

If it does, then maybe Logitech found the existing features (in the HID++ 2.0 sense) not sufficient and added a new one?

**Comment by cgameing** [comment]
I could not find a way to customize dpi in Logitech's setpoint software on a windows os.

Although normaly without solar or another kind of driver you cant customize sensitivity let alone dpi in linux.

**Comment by jrbenito** [comment]
@Lekensteyn ,

This device does not support DPI setting. Let's close this.
