### ISSUE TITLE
Please remove obnoxious popup window

### ISSUE THREAD

**Issue by michaelmrose** [pwr/Solaar#231]
If you want to inform the user that their battery is low changing the tray icon or sending a notification is sufficient.

Poping up a window  that takes focus on the users desktop is horribly annoying more so when it pops up repeatedly especially when it manages to do so in the middle of a game and ruin it.

I would appreciate if there was at least a way to disable this.

**Comment by sheela-na-geek** [comment]
+1. The window is extremely annoying  :(

**Comment by hobarrera** [comment]
A notification via XDG Desktop Notifications would be perfect, IMHO.

**Comment by haarp** [comment]
+1

**Comment by noderat** [comment]
Perhaps one of the contributors comment on this issue? Having the option to disable notifications completely would be nice.

**Comment by johngilbrough** [comment]
I have Solaar on my Ubuntu laptop and I'm getting the annoying notification (image attached) every 60 seconds that my mouse battery is just fine.  This is something you might want to know when you first log on, but not two hundred times a day.  Maybe this isn't Solaar's doing, but how would you know?

![solaar mouse](https://cloud.githubusercontent.com/assets/226320/13199148/56890016-d7eb-11e5-8eda-96f6eb93d571.png)

**Comment by noderat** [comment]
@johngilbrough I'm getting that too, I think it's because the device goes into sleep mode

**Comment by Lekensteyn** [comment]
@noderat Have you tried the latest version from git master? It should have been fixed already

**Comment by johngilbrough** [comment]
Where on git?

**Comment by Lekensteyn** [comment]
git master, this repository. It was fixed by #257

**Comment by johngilbrough** [comment]
I can see the thread that discusses this but nowhere is there a <Download>
button.  Where would I look?  Can you just send me a link to the download
page?

**Comment by Lekensteyn** [comment]
There is a "Clone or download" link in the upper right corner of https://github.com/pwr/Solaar

**Comment by noderat** [comment]
@Lekensteyn I'm not getting battery notifications, it's just saying "Wireless Mouse MX Master Powered On" and then hides in my message tray

**Comment by Lekensteyn** [comment]
@noderat If there has not been an existing report, please open a new issue, preferably with steps to reproduce, the environment (distro, desktop environment, versions) and if it is relevant, the output of `solaar --debug`. (I get notifications for all issues, whether I have time to handle them is another matter ;))

**Comment by noderat** [comment]
@Lekensteyn Will do. I know that story, now I have to find the time to create the new issue as well.
