### ISSUE TITLE
add to ppa-repository versions for ubuntu 14.10 and 15.04

### ISSUE THREAD

**Issue by GlebPoljakov** [pwr/Solaar#232]
Hello, Daniel Pavel!

I am "happy" owner of Logitech K480 and i find way to permanently switch Fn-key from default media-behavior to Fn.
Now i have ubuntu 14.10 on my laptop and i plan to upgrade to 15.04.
I try to install Solaar, but your ppa-repository does not have versions for 14.10 and 15.04.

Daniel Pavel, could you please add support for ubuntu 14.10 and 15.04?

Thanks in advance!

BR,
Gleb.

**Comment by yanndinendal** [comment]
@GlebPoljakov: In the mean time, you can manually update the file /etc/apt/sources.list.d/daniel_pavel-ubuntu-solaar-utopic.list to put 'trusty' instead of the unavailable distrib version, like this:

```
deb http://ppa.launchpad.net/daniel.pavel/solaar/ubuntu trusty main
```

**Comment by skierpage** [comment]
Until this is fixed the section on Solaar's main page about Ubuntu packages should mention the issue, see my pull request pwr/Solaar#236.

**Comment by luisalvarado** [comment]
Updated AskUbuntu's answer about Solaar.

**Comment by Lekensteyn** [comment]
14.10 is EOL and Ubuntu 15.04+ has included Solaar in the universe repo. No PPA version is needed anymore I think.

**Comment by jrbenito** [comment]
@Lekensteyn 

Based on your comment above we can close this.
