### ISSUE TITLE
M705 + K207 = keyboard still "offline" mouse works okay

### ISSUE THREAD

**Issue by Kepro** [pwr/Solaar#238]
Hi,
keyboard K270 is still marked as offline

mouse:

```
Index        : 1
Wireless PID : 101B
Protocol     : HID++ 1.0
Polling rate : 8 ms (125Hz)
Serial       : F0F75C4A
  Firmware   : 17.01.B0017
  Bootloader : 02.06
  Other      : 00.04
Notifications: battery status
```

keyboard

```
Index        : 2
Wireless PID : 4003
Protocol     : HID++ 2.0
Polling rate : 20 ms (50Hz)
Serial       : FD49A73E
  Firmware   : RQK 35.00.B0017
```

**Comment by Kepro** [comment]
today mouse is offline and keyboard is online
yesterday both is online

**Comment by jrbenito** [comment]
@Kepro 

Could you please try to reproduce on latest master commit? If still reproducible, please post debug information.

Keep in mind that devices goes to standby, if not used, even if power switch is on. Use the mouse and keyboard before issue `solaar show` command. Also, GUI might take few moments to update.

If not reproducible we will close this one.

**Comment by Kepro** [comment]
sorry, i stop using solaar, because ubuntu can show me a battery stats of my keyboard and mouse

**Comment by jrbenito** [comment]
@Kepro ,

could you please close this issue? I don´t have permission as you do.

Thanks.
