### ISSUE TITLE
after unpairing a device solaar gui does not work anymore

### ISSUE THREAD

**Issue by hagabla** [pwr/Solaar#241]
solaar gui only shows one device instead of the 3 connected. This behaviour started when i unpaired and repaired a device.
solaar-cli shows all 3 devices:

solaar-cli show
Unifying Receiver [/dev/hidraw0:B5CC977B] with 3 devices
1: Marathon Mouse M705 [M705:514BF81F] 
2: Wireless Keyboard K270 [K270:1F30DDA0] 
3: Performance Mouse MX [Performance MX:3E2F6EB2] 

solaar gui only shows "1: Marathon Mouse M705 ..."
Furthermore gui says "2 paired devices" while showing only one.

**Comment by jrbenito** [comment]
@hagabla ,

What if you quit solaar and open it again?

Can you please try this on latest master commit? If it still reproduces, could you please post debug information?

Thanks

**Comment by hagabla** [comment]
@jrbenito Sorry, i am not using logitech equipment any more :-(

**Comment by jrbenito** [comment]
@hagabla ,

Please, close this issue I will keep investigating under #240. I don´t have permission to close as you do.

thanks.
