### ISSUE TITLE
Please provide more advanced setup for Logitech wheel (left right) in Solaar config

### ISSUE THREAD

**Issue by lovrenco** [pwr/Solaar#243]
For example:
wheel left - browser back
wheel right - browser forward

And specially useful, if you do a lot copy/paste:

wheel left - copy
wheel right - paste

Those things are provided in Logitech driver under Windows. 

Thank you in advance

**Comment by jrbenito** [comment]
@lovrenco,

You shall be able to achieve this by using xbind-keys  and xautomation tools.

**Comment by Lekensteyn** [comment]
On the device/protocol level the key actions cannot be reprogrammed. It would require playing with something like xbindkeys. I guess it is too much work at the moment, let's keep it out of scope for Solaar now.
