### ISSUE TITLE
Performance MX button 10 and button 13 not recognized in ubuntu 15.10

### ISSUE THREAD

**Issue by LuisDiazUgena** [pwr/Solaar#246]
Hi!

I've upgraded a few weeks ago to ubuntu 15.10 from 14.04 and button 10 (show windows button) and 13 (zoom button) of logitech performance mouse mx are not recognized, so I cant use them in ubuntu.

Could be great to have a key configuration tool in solaar, since the computer recognizes the keys as button input, but makes nothing.

Thanks

**Comment by MagicFab** [comment]
For now you will need to:

1. Install xbind-keys and xautomation:
`sudo apt-get install xbind-keys xautomation`

1. Create a default config file for your user:
`xbindkeys --defaults >> ~/.xbindkeysrc`

1. Add this to ~/.xbindkeyrc (including quotes):

```
"xte 'keydown Super_L' 'keydown Alt_L' 'key 8' 'keyup Alt_L' 'keyup Super_L'"
b:13

"xte 'key Super_L'"
release + b:10

```

1. Restart xbindkeys if it was already started and test by pressing your mouse buttons:
`sudo pkill -f xbindkeys && xbindkeys`

1. Once satisfied, logout and login again to make sure it's starting automatically.

**Comment by jrbenito** [comment]
@LuisDiazUgena ,

Solaar is intended to configure the Logitech devices, make (un)paring. What you are asking is handled by input system. I suggest follow @MagicFab  suggestion. 

@Lekensteyn , @LuisDiazUgena 

Old and solved, I think we can close this one.
