### ISSUE TITLE
Installing Solaar on a Raspberry Pi 2 B running rasbian

### ISSUE THREAD

**Issue by daveduggan** [pwr/Solaar#251]
Is it possilbe to run Solaar on a Raspberry Pi 2 B runing Raspian?
If so, how do I install Solaar please?
I am a noob.
thank you

**Comment by ibu2004** [comment]
Follow the instructions here: https://pwr.github.io/Solaar/debian.html

After that, run `sudo apt-get install solaar`

**Comment by jrbenito** [comment]
@Lekensteyn or @daveduggan 

Let´s close this one!
