### ISSUE TITLE
disable Swap Fx function error

### ISSUE THREAD

**Issue by nebuchar** [pwr/Solaar#252]
Using a k750 keyboard, I was able to enable "Swap Fx function", but now, when I try to disable it, it says: "Read/write operation failed", and the option is not saved

![image](https://cloud.githubusercontent.com/assets/1526560/12350145/800866da-bb75-11e5-8472-d48be5dd519a.png)

Using Ubuntu 14.04

**Comment by nebuchar** [comment]
Seems that killing the app solves the problem

**Comment by jrbenito** [comment]
@nebuchar or @Lekensteyn 

If solved, let´s close this one.
