### ISSUE TITLE
Misidentification of M175 mouse as an M185

### ISSUE THREAD

**Issue by SlySven** [pwr/Solaar#255]
This is not a high priority issue :smile:  but I was puzzled when I went to used Solaar to pair an existing M175 mouse that originally had a *nano* receiver which I had lost with a new unifying one - and I was not wanting to have to shut-down and reboot into M$Windoze to do that (I'd get bogged down with yet another *Lose*-10 update opportunity :stuck_out_tongue_winking_eye: !) - I like this project that brings to Linux the features that Logitech can't be a\*\*\*d to provide for a decent OS.  I wonder whether this is a mismatch in a table of values somewhere so provide the `dmesg` output from re-connection of the (now already paired mouse/receiver) into my system:

    [115592.116164] usb 3-1: new full-speed USB device number 2 using ohci-pci
    [115592.288416] usb 3-1: New USB device found, idVendor=046d, idProduct=c52b
    [115592.288428] usb 3-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
    [115592.288435] usb 3-1: Product: USB Receiver
    [115592.288440] usb 3-1: Manufacturer: Logitech
    [115592.310620] logitech-djreceiver 0003:046D:C52B.000A: hiddev0,hidraw1: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:12.0-1/input2
    [115592.367580] input: Logitech Unifying Device. Wireless PID:4008 as /devices/pci0000:00/0000:00:12.0/usb3/3-1/3-1:1.2/0003:046D:C52B.000A/0003:046D:C52B.000B/input/input22
    [115592.367859] logitech-djdevice 0003:046D:C52B.000B: input,hidraw2: USB HID v1.11 Mouse [Logitech Unifying Device. Wireless PID:4008] on usb-0000:00:12.0-1:2

Given the chance I will try and dig around and see where **M175** is being mistaken for **M185** unless someone can tell me that it is a limitation in the software in that it cannot pin down the exact model just from the data available to it (it needs some secret *Logitech* details that they have not let loose).

**Comment by Lekensteyn** [comment]
Looks straightforward, thanks for the patch!

**Comment by petergloor** [comment]
Using solaar 1.1.8+dfsg-2 on a Raspberry Pi 3 with Raspberry Pi OS (Bookworm) it happens the other way round. My M185 is shown as M175 in solaar.

`[   12.110912] input: Logitech M185 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.2/0003:046D:C52B.0003/0003:046D:4008.0004/input/input15
[   12.111678] logitech-hidpp-device 0003:046D:4008.0004: input,hidraw1: USB HID v1.11 Mouse [Logitech M185] on usb-3f980000.usb-1.3/input2:1
[   12.324365] input: Logitech K270 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.2/0003:046D:C52B.0003/0003:046D:4003.0005/input/input16
[   12.402278] logitech-hidpp-device 0003:046D:4003.0005: input,hidraw2: USB HID v1.11 Keyboard [Logitech K270] on usb-3f980000.usb-1.3/input2:2
[   39.669772] logitech-hidpp-device 0003:046D:4003.0005: HID++ 2.0 device connected.
[ 1033.074646] logitech-djreceiver 0003:046D:C52B.0003: device of type eQUAD step 4 DJ (0x04) connected on slot 1
[ 1033.092557] input: Logitech M185 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.2/0003:046D:C52B.0003/0003:046D:4008.0006/input/input17
[ 1033.093603] logitech-hidpp-device 0003:046D:4008.0006: input,hidraw3: USB HID v1.11 Mouse [Logitech M185] on usb-3f980000.usb-1.3/input2:1
`

**Comment by pfps** [comment]
Version 1.1.8 is obsolete.
