### ISSUE TITLE
`solaar-cli show -v` crashes when a Performance MX is charging

### ISSUE THREAD

**Issue by hobarrera** [pwr/Solaar#260]
When my device is charging, `solaar-cli show -v` crashes:

```
$ solaar-cli show -v
Unifying Receiver
   Device path  : /dev/hidraw0
   USB id       : 046d:c52b
   Serial       : 225C9B9A
     Firmware   : 12.01.B0019
     Bootloader : 02.14
   Has 1 paired device(s) out of a maximum of 6 .
   Notifications: 0x000900 = wireless, software present
   Device activity counters: 1=78

1: Performance Mouse MX
   Codename     : Performance MX
   Kind         : mouse
   Wireless PID : 101A
   Protocol     : HID++ 1.0
   Polling rate : 8 ms
   Serial number: 7B0331A0
        Firmware: 15.01.B0062
      Bootloader: 02.11
           Other: 00.09
   The power switch is located on the base.
   Notifications: (none).
Traceback (most recent call last):
  File "/usr/bin/solaar-cli", line 42, in <module>
    solaar.cli.main()
  File "/usr/lib/python3.5/site-packages/solaar/cli.py", line 431, in main
    args.cmd(receiver, args)
  File "/usr/lib/python3.5/site-packages/solaar/cli.py", line 207, in show_devices
    _print_device(dev, args.verbose)
  File "/usr/lib/python3.5/site-packages/solaar/cli.py", line 190, in _print_device
    text = '%d%%' % level
TypeError: %d format: a number is required, not NoneType
```

**Comment by hobarrera** [comment]
It would seem that this is mostly fixed in master (though the status says "N/A, recharging", rather than merely "recharging".

Maybe it's time for a new release? There seems to be a lot of unrelease updates/fixes out.

**Comment by Petross404** [comment]
I noticed that python 3.5 is used. Is this version supported by solaar?

I am asking because in Gentoo, only python2.7 and 3.4 are being used for solaar.

**Comment by Lekensteyn** [comment]
@Petross404 Python 3.5 should be supported. If you have the same issue, have you tried git master?

@hobarrera Would not be a bad idea after going through the existing issues. No timeline though.

**Comment by Petross404** [comment]
@Lekensteyn Python 3.5 is indeed supported. I am going to report a bug for the Gentoo's ebuild to enable it.
Also I had the same issue described above and I updated to git master which merely solved it.
`solaar show 
Unifying Receiver
  Device path  : /dev/hidraw2
  USB id       : 046d:c52b
  Serial       : 3E7993E1
    Firmware   : 12.01.B0019
    Bootloader : 02.14
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=245

  1: Performance Mouse MX
     Codename     : Performance MX
     Kind         : mouse
     Wireless PID : 101A
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: 470906F9
          Firmware: 15.01.B0062
        Bootloader: 02.11
             Other: 00.09
     The power switch is located on the base.
     Notifications: battery status (0x100000).
     Battery: N/A, recharging.
`

Last, I made a live ebuild for solaar. Let's see if it is accepted.

**Comment by Lekensteyn** [comment]
@hobarrera Did you just added the milestone or does Github have a bug? I also just clicked the milestone link.

Closing this issue as the bug is reportedly resolved in master.
