### ISSUE TITLE
Battery status is wrong

### ISSUE THREAD

**Issue by hfarazi** [pwr/Solaar#273]
I use MXanywhere2 mouse and it seems that although the charge percentage is correct on my mac logitech software, in "Solaar" it is wrong. (it can jump from 0 to 90 to 50%).

**Comment by hmksq** [comment]
The Logitech program (Windows) only displays like "Good" and not by percent. I think It should be replaced with something similar or both (if there are some devices which gives detailed percentage)

**Comment by jrbenito** [comment]
@hfarazi ,

Are you able to reproduce this issue on latest commit from maser branch? How about from branch `anywhere2` on my personal [clone](https://github.com/jrbenito/solaar)? 

Thanks.

**Comment by Lekensteyn** [comment]
@hfarazi There are only four levels of granularity for most models, it cannot be made more precise.

Just consider the text labels (critical, low, high, full) or something like that.
