### ISSUE TITLE
Specfy Gtk version in gtk.py

### ISSUE THREAD

**Issue by daoswald** [pwr/Solaar#278]
When one starts solaar from the command line under Ubuntu linux 16.04 a warning is generated about the need to specify a version for Gtk:

$ solaar
/usr/share/solaar/lib/solaar/gtk.py:33: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.

**Comment by jrbenito** [comment]
This issue seems to be solved on master branch.

Could you please confirm and close?

**Comment by Lekensteyn** [comment]
This was fixed in e1eee2e078ae986bb2e0947ce5a0ddca888a23ba
