### ISSUE TITLE
GPG key change?

### ISSUE THREAD

**Issue by dukedave** [pwr/Solaar#281]
I have [the PPA](https://launchpad.net/~daniel.pavel/+archive/ubuntu/solaar) added, but since yesterday when I `apt-get update`, I saw:

```
W: GPG error: http://ppa.launchpad.net trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 90AACB8406524FBA
```

I followed the advice [here](http://askubuntu.com/a/520831/82469) and got this output:

```
gpg: key 06524FBA: public key "Launchpad PPA for Daniel Pavel" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```

Googling _Daniel Pavel_ then led me to here.
---

I can now run `apt-get update` without the `GPG error`, but I thought I'd log an issue here in case others see it, and to make Daniel aware.

**Comment by Lekensteyn** [comment]
These GPG keys are created by Launchpad, could it be that it got removed due to an dist upgrade?

**Comment by Lekensteyn** [comment]
No response, closing. Re-open if you still have issues. Thanks!
