### ISSUE TITLE
Question: support function keys swapping on K400 plus?

### ISSUE THREAD

**Issue by LuciferSam86** [pwr/Solaar#282]
Hello everybody,
does latest version of solaar supports function keys swapping or not?
If not: could I configure the keyboard on a Windows machine and the reconnect to Linux machine and the keyboard "remembers" the setting?

**Comment by Lekensteyn** [comment]
Function key swapping is supported, the keyboard does not remember the state though. This should be handled by software like Solaar.

**Comment by v01d** [comment]
I'm trying to swap FN key state on K400 plus with solar and it does not appear to be configurable:

    [v01d@kanji ~]$ solaar-cli config 1
    solaar-cli: error: no settings for Wireless Touch Keyboard K400 Plus

**Comment by PRJosh** [comment]
Same here.

**Comment by v01d** [comment]
Btw, in latest master I do have support for this. It seems it is simply not
in the latest release.

**Comment by PRJosh** [comment]
You are correct, master has the feature. Thanks!

**Comment by PRJosh** [comment]
Unfortunately now I get "read write operation failed" when I try to switch it :/

**Comment by Magnesus** [comment]
How about k780?

**Comment by Lekensteyn** [comment]
@Magnesus If the device is a recent one, support for such features should automatically be detected.

**Comment by kubino** [comment]
I can swap fn keys on master on my Wireless Touch Keyboard K400 Plus   Thx a lot!

**Comment by Lekensteyn** [comment]
Question should be solved, so closing issue.

**Comment by alfC** [comment]
@kubino Hi, can you tell how you swapped you Fn, what command did you use? 

I get this

```
$ solaar config 3 
solaar: error: no settings for Wireless Touch Keyboard K400 Plus
```

**Comment by Lekensteyn** [comment]
@alfC Presumably it is related to the HID++ version, see #308

**Comment by kubino** [comment]
@alfC  my command is -  solaar/bin/solaar config 0 fn-swap off

but as mentioned above it only worked with latest master branch for me

**Comment by kubino** [comment]
I did used master at this commit 1edd8a577bade85bbf9e2e3c9591f04caea45931

Not sure how it is with latest one

**Comment by jrbenito** [comment]
@kubino ,

Are you able to test on latest master just to confirm it still work? I did a full diff between 1edd8a5 and master, I think there is nothing there that could break compatibility with K400plus, but a confirmation with real device would be great.

Thanks

**Comment by kubino** [comment]
@jrbenito 

yes, just pulled and tried as usual, keys get swapped ;) thx again

**Comment by Lekensteyn** [comment]
Thanks for confirming!
