### ISSUE TITLE
Please merge es.po language update

### ISSUE THREAD

**Issue by MagicFab** [pwr/Solaar#286]
I submitted this a few months ago, it would be nice if it could be merged:
https://github.com/pwr/Solaar/pull/263

Thank you!

**Comment by Lekensteyn** [comment]
Merged in fa5fba7, thanks! Next time you can also just ping on the issue :)

**Comment by MagicFab** [comment]
Thank you! Ping where? EMail?

**Comment by Lekensteyn** [comment]
Reply to the issue for example.
