### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by alex9099** [pwr/Solaar#291]
Hi, i'm reciving this error:
 `UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)`

when running either the solaar or the solaar cli python script on the bin folder,

already applied the udev rules and it works fine with the packege that is on ubuntu but i need to swap the fn keys, and that options is marked as unsuported, from what i saw it is supported on the master version (the one i downloaded) from what says on this bug : https://github.com/pwr/Solaar/issues/282

Can you solve that error?

**Comment by alex9099** [comment]
Nevermind... you can close this issue, it was because the code was on a path with non unicode chars like /home/user/Transferências/solaar

Thanks for this code, it worked fine on the k400 plus /touch to change the fn key function :+1:

**Comment by jrbenito** [comment]
@alex9099 ,

Please, close this issue. Since you opened it you have the permission to close. @Lekensteyn  also can do it but he is busy trying to cope his time with lot of issues and PRs.

Thanks!

**Comment by Lekensteyn** [comment]
I think it is a bug worth looking into, non-Unicode paths should probably be gracefully handled.

@jrbenito Thanks for your assistance in cleaning up bugs :+1: Do you think that you can also test the reported scenario and maybe propose a patch? I guess it is not that high priority since you normally do not encounter it though.

**Comment by jrbenito** [comment]
@Lekensteyn 

Agreed. Did not think this way.

Yes, I will test and try solve it.

**Comment by alex9099** [comment]
If it is corrected i may close it

**Comment by jrbenito** [comment]
Better to wait it to be merged

**Comment by alex9099** [comment]
ok

**Comment by jrbenito** [comment]
@alex9099 ,

If you want give it a try, clone my repo and checkout UTF8 branch, run solaar from inside.
