### ISSUE TITLE
How can I disable smartshift with the MX Master

### ISSUE THREAD

**Issue by ashic** [pwr/Solaar#293]
I installed solaar from the ppa, and it detects my MX Master in the Solaar GUI. However, I can't find a way to change any of the settings. I'd like to disable smartshift completely. Is the usage documented somewhere?

**Comment by Lekensteyn** [comment]
The PPA is outdated, try to install it from git master. Unfortunately I do not have access to the PPA, only this repo.

**Comment by jrbenito** [comment]
@ashic ,

If solved, please close this issue.

@Lekensteyn ,

Can we somehow get access or at create a new PPA? many people don´t want to install by hand or simply don´t know how. A .deb available for them would be great and PPA is really outdated. 

Please share your thoughts

**Comment by Lekensteyn** [comment]
@jrbenito I can try to setup a PPA, but would then have to do some QA on it.

Would you be willing to test it once it gets up? What distro (version) are you using?

**Comment by jrbenito** [comment]
@Lekensteyn 

I can help, I use Ubuntu 16,04.

**Comment by Lekensteyn** [comment]
@jrbenito  Ok, I'll put creating a new PPA on my to-do list. Don't expect anything soon though ;)

@ashic I'm closing this because it should supposedly be fixed in the development version (git master branch). If you still experience issues, please reopen.
