### ISSUE TITLE
How can I uninstall solaar?

### ISSUE THREAD

**Issue by davidbayo10** [pwr/Solaar#299]
I installed solaar with setup.py script and now, I want to uninstall it. How can i do it?

**Comment by Lekensteyn** [comment]
There does not seem to be a standard uninstall target. For generic instructions, see:
https://stackoverflow.com/questions/1550226/python-setup-py-uninstall

**Comment by jrbenito** [comment]
@davidbayo10 ,

If the answer solves your problem I think it is best to close this issue.

Thanks

**Comment by Lekensteyn** [comment]
I'll go ahead and close this one, please reopen if you still have issues. Thanks!
