### ISSUE TITLE
Support Fn swap/Invert scrolling on Logitech K400 Plus

### ISSUE THREAD

**Issue by cmeeren** [pwr/Solaar#325]
There doesn't seem to be any settings available for Logitech K400 Plus:

```
$ solaar-cli config 1
solaar-cli: error: no settings for Wireless Touch Keyboard K400 Plus
```

The lack of normal Fn operation is driving me nuts. Is there any chance you could implement support for Fn swap? 🙏 

Some further diagnostic information:

```
$ solaar-cli show
Unifying Receiver [/dev/hidraw1:********] with 1 devices
1: Wireless Touch Keyboard K400 Plus [K400 Plus:********]
```

Unifying Receiver selected in Solaar GUI:
```
Path         : /dev/hidraw1
USB id       : 046d:c52b
Serial       : ********
  Firmware   : 24.01.B0023
  Bootloader : 01.08
  Other      : AA.AC
Notifications: wireless
               software present
```

K400 Plus selected in Solaar GUI:
```
Index        : 1
Wireless PID : 404D
Protocol     : HID++ 4.1
Polling rate : 8 ms (125Hz)
Serial       : ********
  Bootloader : BOT 22.01.B0001
  Firmware   : RQK 63.01.B0014
  Other      : 
```

Let me know if you need any other information.

**Comment by Lekensteyn** [comment]
Have you tried the version from git? It is supposed to be supported.

**Comment by cmeeren** [comment]
I'm using Solaar 0.9.2, installed from APT. This also seems to be the latest release here on GH. Or are you thinking of compiling the master branch myself?

Also, note that K400 Plus is not listed in the Device list (K400 Touch is, however).

**Comment by Lekensteyn** [comment]
0.9.2 is outdated, master has a lot unreleased fixes and is listed in docs/devices.md (in master, not the website)

**Comment by cmeeren** [comment]
Thank you, that worked - I'm able to swap Fn function now. () Do you plan on releasing a new version anytime?

Also, are you considering enabling reversed scroll direction for this keyboard?

**Comment by Lekensteyn** [comment]
Can you run `solaar show` to list supported features? That would allow checking if reverting scroll direction is possible on the protocol level. Plan to release new version? Yes. Any time soon? Maybe I'll try for a release in February, it is a bit busy period now ;)

...but you are probably much better off with a xinput/libinput-specific configuration option. (Your desktop environment might offer such an option for the mouse settings.)

**Comment by cmeeren** [comment]
Unfortunately the touchpad settings under "Mouse and Touchpad" in Linux Mint do not seem to affect the keyboard's touchpad.

Output of `solaar show`:
````
Unifying Receiver
  Device path  : /dev/hidraw7
  USB id       : 046d:c52b
  Serial       : ********
    Firmware   : 24.01.B0023
    Bootloader : 01.08
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=113

  1: Wireless Touch Keyboard K400 Plus
     Codename     : Plus
     Kind         : keyboard
     Wireless PID : 404D
     Protocol     : HID++ 4.1
     Polling rate : 8 ms (125Hz)
     Serial number:  ********
        Bootloader: BOT 22.01.B0001
          Firmware: RQK 63.01.B0014
             Other: 
     The power switch is located on the top edge.
     Supports 24 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: REPROG CONTROLS V4     {1B04}   
         8: SWAP BUTTON            {2005}   
         9: NEW FN INVERSION       {40A2}   
        10: ENCRYPTION             {4100}   
        11: KEYBOARD DISABLE       {4521}   
        12: TOUCHPAD RAW XY        {6100}   
        13: GESTURE 2              {6501}   
        14: DFUCONTROL 2           {00C1}   
        15: unknown:1811           {1811}   internal, hidden
        16: unknown:1830           {1830}   internal, hidden
        17: unknown:1890           {1890}   internal, hidden
        18: unknown:1DF3           {1DF3}   internal, hidden
        19: unknown:1E00           {1E00}   hidden
        20: unknown:1EB0           {1EB0}   internal, hidden
        21: unknown:1861           {1861}   internal, hidden
        22: unknown:18B0           {18B0}   internal, hidden
        23: unknown:1F11           {1F11}   internal, hidden
     Battery: 90%, discharging.
````

**Comment by Lekensteyn** [comment]
FN inversion is working (setting `new_fn_swap`, feature `NEW_FN_INVERSION`). There does not seem to be firmware options to swap the scrolling direction (but again, this should be handled by libinput).

For reverse scrolling directions, please search for ways to do this with libinput (or xinput if you are still using an old distro).

**Comment by cmeeren** [comment]
For the record, here's the scrolling direction fix that worked for me: http://askubuntu.com/a/519859/667293

**Comment by cmeeren** [comment]
For the record again, I had to modify the procedure a bit, because the answer I linked to reversed even the scroll wheel on my mouse.

Here's a script that I run on startup that fixes the K400 touchpad:

```
DEVICE_ID=$(xinput list | grep "Logitech K400 Plus" | sed -n 's/.*id=\([0-9]*\).*/\1/p')
PROPERTY_NUM=$(xinput list-props $DEVICE_ID | grep "Scrolling Distance" | sed -n 's/.*(\([0-9]*\)).*/\1/p')
xinput set-prop $DEVICE_ID $PROPERTY_NUM -1 -1 -1
```

**Comment by Zainpro** [comment]
Hi,                          
I copied the script on terminal and it works perfect however, when I add it to /etc/rc.local it does not run or take any effect. How do you run it on start up?

**Comment by Lekensteyn** [comment]
@Zainpro `xinput` requires a X server to be present. Try searching for a way to autostart a program within your desktop environment (or even display manager like SDDM).
