### ISSUE TITLE
MX Master confuses libinput

### ISSUE THREAD

**Issue by Tustvold** [pwr/Solaar#355]
I'm having a strange issue using the MX Master on Arch linux with the provided RF dongle.

On login the desired "libinput Accel Speed" is set by the gnome settings daemon to -0.8.

On resume this setting seems to be forgotten, whilst running "xinput list-props" still reports that  "libinput Accel Speed" is -0.8, it clearly is actually set to 0. Manually setting the accel speed to -0.8 fixes this, but I'm unsure why libinput is either incorrectly applying or incorrectly reporting the accel speed?

Is there a way to fix this, or failing that run a script to automatically set the accel speed after the mouse has reconnected?

**Comment by Lekensteyn** [comment]
If gnome-settings daemon changes the libinput accel speed (and not Solaar), then gnome-settings should also change the setting when the mouse resumes from power save.

I suggest reporting this issue against the gnome-settings issue tracker.

As workaround I guess that you can invoke `xinput set-prop "..." "lininput Accel Speed" -0.8` (where `...` is the name reported by `xinput list`) after resume.

**Comment by Tustvold** [comment]
That's what I'm currently doing, it is just rather annoying having to do it manually. I've had no luck getting a systemd script to work, I think gnome is trampling over whatever it sets. I've ordered a bluetooth dongle and hopefully that will solve the problem.

**Comment by Tustvold** [comment]
Bluetooth dongle didn't fix issue, but I now believe this is a problem with gnome-settings daemon and not solaar so closing this issue report.
