### ISSUE TITLE
Manual installation instructions for noobs

### ISSUE THREAD

**Issue by adityabhaskar** [pwr/Solaar#363]
Hi

Would anyone be able to provide manual installation for a noob.

I'm on Ubuntu Zesty. The version in the Ubuntu repository is 3+ years old, and doesn't support <kbd>Fn</kbd> key swap for one of my keyboards.

I've tried a couple of alternate repositories as well, but neither has a new version for zesty.

I tried going through the instructions on the manual installation page, but either I'm too much of a noob, or there are a few steps missing there. Either way, I didn't make any progress.

I would really love some help if someone could share detailed, noob-friendly instructions on installing Solaar from this repository.

Cheers!

Adi

**Comment by ArtyV** [comment]
It's rather easy :)
Download the GITHUB 
Extract the zip
open that main folder into terminal

run : sudo python setup.py install

**Comment by adityabhaskar** [comment]
Thanks @ArtyV 

Can't believe it was so simple, yet I missed it.

For anyone who may come across this, you may need one more step after the one mentioned above:

1. `sudo python setup.py install`
2. `sudo rules.d/install.sh`
3. Remove and resinsert the USB receiver, and you are ready to go.

Cheers!

Adi
