### ISSUE TITLE
Interested in hardware?

### ISSUE THREAD

**Issue by sixtyfive** [pwr/Solaar#368]
Hi, I have an M235 2nd gen. that doesn't seem to be supported ("Unknown device") and that I don't need anymore as I just bought a new mouse that better fits my hands. Are you interested in hardware such as this and if so, what address can I mail it to?

**Comment by jrbenito** [comment]
Hi,

I would work on the support but I leave in Brazil and have no idea how much would cost to ship it here. If you are interested please contact me in private.

regards,

**Comment by sixtyfive** [comment]
Done.
