### ISSUE TITLE
Software won't update error RQR12.07_B0029

### ISSUE THREAD

**Issue by bsthinker** [pwr/Solaar#376]
I receive an error message indicating that the release an unencrypted injection.
There is also a red error message indicating that the device cannot be plugged in during update.

I unplug, the message goes away.  I plug in the receive, the message shows up again.

**Comment by arigit** [comment]
This is likely related to fwupd,  the firmware update daemon / service and nothing to do with solaar.  You probably have an unsupported Unifying receiver (know issue, patch available coming in a future fedora release, I think) such as the one that comes with the Mx Anywhere.
For now, you could just uninstall the fwupd package.
This isuue does not really belong to solaar.

**Comment by Lekensteyn** [comment]
Solaar does not support firmware update yet, please close it before updating firmware through fwupd, otherwise you will get strange warnings and may fail the update.
