### ISSUE TITLE
Solaar, Logitech K360 Keyboard, Manjaro-Gnome 17.02 Kernnel 4.9 

### ISSUE THREAD

**Issue by WashuHanb** [pwr/Solaar#380]
Plain Solaar is instaled.  the K360 is shown on the list of devices but it battery and Wireless state is unknown and the Swap Fx Function switch doesn't move.  Clicking does produce a a write on what the change just did though.   Shows Technical details button works.

Looks like the K360 isn't fully working in Solaar 0.9.2.

The keyboard works fine though.

**Comment by Lekensteyn** [comment]
Please try with git master and re-open if the problem still appears to exist.
