### ISSUE TITLE
solaar-git available at archlinuxcn repository

### ISSUE THREAD

**Issue by heavysink** [pwr/Solaar#381]
Hi,

The git version of solaar is now available at archlinuxcn repo and the archlinuxcn buildbot will be automatically update the package with any update github repository here. The repo is here:

[archlinuxcn]
Server = http://repo.archlinuxcn.org/$arch
add it into /etc/pacman.conf and follow the instructions https://wiki.archlinux.org/index.php/unofficial_user_repositories#archlinuxcn

sudo pacman -S solaar-git after adding the repo.

**Comment by Lekensteyn** [comment]
Thanks for the heads-up. Since third-party repositories are not supported officially by Arch Linux, I think there is not much documentation to change right?

**Comment by heavysink** [comment]
@Lekensteyn I think so.

**Comment by Lekensteyn** [comment]
Ok, then I'm closing this issue!
