### ISSUE TITLE
K400plus F key inversion

### ISSUE THREAD

**Issue by mhodgessss** [pwr/Solaar#386]
Unfortunately the successor to K400 requires the FN button to get to F1 to F12.
Any chance of getting this fixed? Can I help?
lsusb
Bus 004 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 007: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 003 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 046d:0828 Logitech, Inc. HD Webcam B990
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

solaar-cli show 1 -v
1: Wireless Touch Keyboard K400 Plus
   Codename     : K400 Plus
   Kind         : keyboard
   Wireless PID : 404D
   Protocol     : HID++ 4.1
   Polling rate : 8 ms
   Serial number: 3800BC70
      Bootloader: BOT 22.01.B0001
        Firmware: RQK 63.01.B0014
           Other:
   The power switch is located on the top edge.
   Supports 24 HID++ 2.0 features:
       0: ROOT                   {0000}
       1: FEATURE SET            {0001}
       2: DEVICE FW VERSION      {0003}
       3: DEVICE NAME            {0005}
       4: WIRELESS DEVICE STATUS {1D4B}
       5: unknown:0020           {0020}
       6: BATTERY STATUS         {1000}
       7: unknown:1B04           {1B04}
       8: unknown:2005           {2005}
       9: NEW FN INVERSION       {40A2}
      10: ENCRYPTION             {4100}
      11: unknown:4521           {4521}
      12: TOUCHPAD RAW XY        {6100}
      13: unknown:6501           {6501}
      14: unknown:00C1           {00C1}
      15: unknown:1811           {1811}   internal, hidden
      16: unknown:1830           {1830}   internal, hidden
      17: unknown:1890           {1890}   internal, hidden
      18: unknown:1DF3           {1DF3}   internal, hidden
      19: unknown:1E00           {1E00}   hidden
      20: unknown:1EB0           {1EB0}   internal, hidden
      21: unknown:1861           {1861}   internal, hidden
      22: unknown:18B0           {18B0}   internal, hidden
      23: unknown:1F11           {1F11}   internal, hidden
   Battery status unavailable.

**Comment by jrbenito** [comment]
Did you try the latest sollar-git (master branch)?

**Comment by mhodgessss** [comment]
Eeem no. This was with the 0.92 distribution built package Debian/jessie. I will pull and build.

**Comment by mhodgessss** [comment]
Yes it works. You can add K400plus to the list of supported devices.

**Comment by Lekensteyn** [comment]
It's already in descriptors.py, but not in devices.md. Updated to docs/devices.md are welcome!

Closing since it is reportedly working.
