### ISSUE TITLE
Improve help contents

### ISSUE THREAD

**Issue by rjhorn-agfa** [pwr/Solaar#389]
The solaar-cli does not mention the -v option, which is needed to view battery levels among other things.

I suggest changing
 show                show information about paired devices
to
 show  [-v]              show information about paired devices, [-v for details]

**Comment by Lekensteyn** [comment]
You can find specific help for an option with `solaar show -h`. It works like this because `show` is a subcommand.

Also note that `solaar-cli` is deprecated, `solaar` has integrated the CLI options. That tool has no `-v` option anymore since the default output is verbose :-)
