### ISSUE TITLE
deb package depends on non-existent gnome-icon-theme-full | oxygen-icon-theme-complete on all current Debian and Ubuntu archives

### ISSUE THREAD

**Issue by jean-christophe-manciot** [pwr/Solaar#420]
@Lekensteyn @pwr
Ubuntu 17.10
commit 59b7285fdfc875119f0c92cfd5f5909e8a8e578c

Building with ```./build_deb.sh``` leads to:
```
# dpkg -I solaar_0.9.2-3~git20180202.59b7285_all.deb 
 new Debian package, version 2.0.
 Package: solaar
 Version: 0.9.2-3~git20180202.59b7285
 Architecture: all
 Maintainer: Daniel Pavel <daniel.pavel@gmail.com>
 Installed-Size: 541
 Depends: debconf (>= 0.5) | debconf-2.0, udev (>= 175), passwd | adduser, python:any (>= 2.7), python-pyudev (>= 0.13), python-gi (>= 3.2), gir1.2-gtk-3.0 (>= 3.4), gnome-icon-theme-full | oxygen-icon-theme-complete
...
```
But on current Ubuntu Artful/Debian Stretch, neither gnome-icon-theme-full nor oxygen-icon-theme-complete exist:
![gnome-icon-theme-full debian](https://user-images.githubusercontent.com/13176858/37841424-04194dee-2ec0-11e8-8fec-6b449a05187e.png)
![gnome-icon-theme-full ubuntu](https://user-images.githubusercontent.com/13176858/37841428-0870c764-2ec0-11e8-9eaa-7889e1f668eb.png)
![oxygen-icon-theme-complete ubuntu](https://user-images.githubusercontent.com/13176858/37841549-4854cb46-2ec0-11e8-946e-0d1849412739.png)

**Comment by jean-christophe-manciot** [comment]
Maybe ```gnome-icon-theme``` is a valid replacement.

**Comment by MagicFab** [comment]
For Debian packages updates, see #288 . tl;dr: there aren't any at the moment.

**Comment by jean-christophe-manciot** [comment]
I offer solaar builds with correct dependencies for the latest git commit:
-  [Ubuntu disco](https://git.sdxlive.com/PPA/about/): unstable component
-  [Debian buster](https://git.sdxlive.com/DR/about/): unstable component

**Comment by Lekensteyn** [comment]
Feel free to open a PR with the correct dependencies, I have not looked into the appropriate dependencies.
