### ISSUE TITLE
MX Master 2S: Listed as offline after autostart

### ISSUE THREAD

**Issue by steffenhaug** [pwr/Solaar#427]
I am using the MX Master 2S mouse.

I am also using Ubuntu 17.10, with Gnome 3.26.2 and solaar 0.9.2 (output of `solaar -V`, but cloned from master so it should be up to date). I followed the [manual instructions](https://github.com/pwr/Solaar/blob/master/docs/installation.md), (running `install.sh`), and have verified that my user is in the `plugdev` group, and that the rules file is really in `/etc/udev/rules.d/`.

Additionally, i ran the script `setup.py`, (`sudo python3 setup.py install`) even though this is not in the installation instructions, because this is roughly what the pkgbuild for solaar-git in the AUR does.

I can execute solaar from the terminal, and it works perfectly. _However_, when autostarted, the program looks like it fails to detect the mouse (claims it is offline, but is does show up). Despite this, it _does work_, but my settings does not load. (maybe it falls back to the default mouse drivers?) Most crucially, the dpi seems to be back at 1000dpi, which is far too low for me.

![fuck](https://user-images.githubusercontent.com/11167607/38633753-de3855b0-3dc0-11e8-95ac-004183a7dcbd.png)

The .desktop file responsible for autostarting (`~/.config/autostart/solaar.desktop`):
```
[desktop entry]
name=solaar
comment=logitech unifying receiver peripherals manager
exec=solaar
icon=solaar
terminal=false
type=application
x-gnome-autostart-enabled=true
```

If i kill it, and start it manually it works _perfectly_ again (with the correct settings).
```
killall solaar
solaar & disown
```
![good_shit](https://user-images.githubusercontent.com/11167607/38633757-e502df14-3dc0-11e8-92a9-cae923105ad0.png)

**Is this not the right way to autostart the program?** If it is not, then this should probably be documented somewhere.

Here is the output from `solaar show`if it is interesting.
```
Unifying Receiver
  Device path  : /dev/hidraw3
  USB id       : 046d:c52b
  Serial       : 88309933
    Firmware   : 24.01.B0023
    Bootloader : 01.08
    Other      : AA.AC
  Has 1 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=202

  1: Wireless Mouse MX Master 2S
     Codename     : MX Master 2S
     Kind         : mouse
     Wireless PID : 4069
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 3A63E457
        Bootloader: BOT 56.00.B0003
          Firmware: MPM 12.00.B0003
          Firmware: MPM 12.00.B0003
             Other: 
     The power switch is located on the base.
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
         3: DEVICE NAME            {0005}   
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: BATTERY STATUS         {1000}   
         7: unknown:1806           {1806}   internal, hidden
         8: CHANGE HOST            {1814}   
         9: REPROG CONTROLS V4     {1B04}   
        10: ADJUSTABLE DPI         {2201}   
        11: VERTICAL SCROLLING     {2100}   
        12: SMART SHIFT            {2110}   
        13: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert
              Normal wheel motion
            Has ratchet switch
              Normal wheel mode
            Low resolution mode
            HID notification
        14: GESTURE 2              {6501}   
        15: DFUCONTROL 2           {00C1}   
        16: unknown:00C2           {00C2}   
        17: unknown:1813           {1813}   internal, hidden
        18: unknown:1830           {1830}   internal, hidden
        19: unknown:1890           {1890}   internal, hidden
        20: unknown:1891           {1891}   internal, hidden
        21: unknown:18A1           {18A1}   internal, hidden
        22: unknown:18C0           {18C0}   internal, hidden
        23: unknown:1DF3           {1DF3}   internal, hidden
        24: unknown:1E00           {1E00}   hidden
        25: unknown:1EB0           {1EB0}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: unknown:1861           {1861}   internal, hidden
        28: unknown:9001           {9001}   internal, hidden
        29: unknown:9200           {9200}   internal, hidden
        30: unknown:9240           {9240}   internal, hidden
        31: unknown:1805           {1805}   internal, hidden
     Has 8 reprogrammable keys:
         0: LEFT CLICK                , default: LeftClick                   => LEFT CLICK                
             mse, pos:0, group:1, gmask:1
         1: RIGHT CLICK               , default: RightClick                  => RIGHT CLICK               
             mse, pos:0, group:1, gmask:1
         2: MIDDLE BUTTON             , default: MiddleMouseButton           => MIDDLE BUTTON             
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         3: BACK AS BUTTON 4          , default: BackEx                      => BACK AS BUTTON 4          
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
         4: FORWARD AS BUTTON 5       , default: BrowserForwardEx            => FORWARD AS BUTTON 5       
             mse, reprogrammable, divertable, pos:0, group:2, gmask:3
         5: unknown:00C3              , default: unknown:00A9                => unknown:00C3              
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         6: unknown:00C4              , default: unknown:009D                => unknown:00C4              
             mse, reprogrammable, divertable, pos:0, group:3, gmask:7
         7: unknown:00D7              , default: unknown:00B4                => unknown:00D7              
             divertable, virtual, pos:0, group:4, gmask:0
     Battery: 50%, discharging.
```

**Comment by duckduck1** [comment]
I do experience the same problem.
Though the MX Master 2S gets detected if I move the mouse before X autostarts solaar.

The problem doesn't exist with the MX Master.

**Comment by AlexWayfer** [comment]
The same.

```
gdm 3.28.1
gnome-shell 3.28.2
```

**Comment by krrk** [comment]
I have the same problem with MX Master

**Comment by jasontibbitts** [comment]
Just a adding that I also have the same issue using an MX Master.  I am using the Fedora packaging, which contains a git snapshot which is current as of 59b7285fdfc875119f0c92cfd5f5909e8a8e578c.

**Comment by arigit** [comment]
+1

**Comment by Lekensteyn** [comment]
Could you try the latest master? Perhaps #452 solves this issue.

**Comment by arigit** [comment]
It appears to be fixed when starting solaar like so:

solaar --restart-on-wake-up

Before #452 was merged, solaar could survive suspend/resume but would have issues after resuming from hibernation. It now appears to be stable in all situations (still using restart-on-wake-up although I am unclear on whether it is still needed)

**Comment by jasontibbitts** [comment]
I can confirm that the current git head fixes the issue with my MX Master not being detected when solaar is autostarted.  I do not need `--restart-on-wake-up` for things to work (though it might of course needed for other reasons).

**Comment by Lekensteyn** [comment]
Thanks for testing, marking as solved! I hope to make a release within a few weeks after migrating the whole repo as described in #407, if you have any feedback for the migration, please reply to that issue.
