### ISSUE TITLE
Support for MK260 receiver

### ISSUE THREAD

**Issue by miquecg** [pwr/Solaar#472]
Hi,

I have a Logitech mouse and keyboard combo MK 250. Device is listed as below:

```
Bus 002 Device 004: ID 046d:c52e Logitech, Inc. MK260 Wireless Combo Receiver
```

I have installed Solaar 0.9.2 in Arch Linux but it doesn't detect my receiver. Is it supported? :thinking:

**Comment by doctor64** [comment]
Must be supported in master branch. Unfortunately 0.9.2 release is very old.

**Comment by miquecg** [comment]
Thanks for the info :+1:

**Comment by doctor64** [comment]
Is it works for you? Can you provide output of solaar show for documentation?

**Comment by doctor64** [comment]
Is it works for you? Can you provide output of solaar show for documentation?

**Comment by miquecg** [comment]
```
Unifying Receiver
  Device path  : /dev/hidraw1
  USB id       : 046d:c52e
  Serial       : xxxxxxxx
    Firmware   : 15.00.B0048
  Has 2 paired device(s) out of a maximum of 2.
  Notifications: (none)

  1: ? (101E)
     Codename     : ? (101E)
     Kind         : mouse
     Wireless PID : 101E
     Protocol     : HID++ 1.0
     Polling rate : 8 ms (125Hz)
     Serial number: xxxxxxxx
          Firmware: 19.02.B0032
     The power switch is located on the (unknown).
     Notifications: (none).
     Battery: good, discharging.

  2: ? (200E)
     Codename     : ? (200E)
     Kind         : keyboard
     Wireless PID : 200E
     Protocol     : HID++ 1.0
     Polling rate : 20 ms (50Hz)
     Serial number: xxxxxxxx
          Firmware: 18.00.B0021
     The power switch is located on the (unknown).
     Notifications: (none).
     Battery: full, discharging.
```

By the way, I have problems with the keyboard after resuming from sleep mode. It takes a while until I can type anything, however the mouse works as expected. Even a hard reboot of the computer doesn't solve the problem immediately. Any idea? :thinking:

**Comment by doctor64** [comment]
Thank you. I was hoping to get some info from output. Unfortunately, this device use old HID++ 1.0 protocol and require knowledge of its registers (or painful process of reverse engineering) to get some controls. 
About your problem after resume - sorry, i can't help here. I don't have any HID++ 1.0 device, except much older ancestor of HID++ 1.0 - EX100 kit.   All I can say - it's not Solaar to blame :). Solaar basically only query/set some values from registers/features. Solaar can report battery status or enable some features like Fn inversion or pointer speed, but don't take part in input processing. It's all done by kernel drivers and/or X Window. Only some tracing at this level (kernel driver4 tracing, usb tracing) can give some information here. 
Just a idea - is this keyboard have power switch? Do you try to power cycle keyboard after resume?

**Comment by miquecg** [comment]
I've tried that, also sawpping the batteries, changing the receiver to another USB port... but nothing proves to fix the problem 100% of the times.

**Comment by doctor64** [comment]
Sorry to hear what. I try to reproduce your issue on my EX100, but not see any problems with suspend-resume. I can think only about usb tracing, to check if receiver send some packets after resume when key pressed on keyboard. At least it give information where is a problem - in logitech hardware or in linux drivers stack.

**Comment by miquecg** [comment]
Thanks for the tip. I've found https://www.kernel.org/doc/Documentation/usb/usbmon.txt This could do the job, right? But debugging has to be in place the moment after resuming, otherwise I'm stucked hehe.

**Comment by doctor64** [comment]
Sorry, can't help here, never used this tool. I have access to hardware protocol analyzer so i can just capture usb exchanges on wire. 
Theoretically speaking, yes, you can perform resume and start packet capture on USB. As I understand, keyboard not work after resume for noticeable time?
By the way, did this happen under Windows?

**Comment by miquecg** [comment]
I didn't try on Windows. Let's see if I can do some useful debugging with `usbmon` or something similar.

Thanks!
