### ISSUE TITLE
Duplicated wpid caused error and assertion failed

### ISSUE THREAD

**Issue by PeterDaveHello** [pwr/Solaar#499]
Looks like `Wireless Mouse M235` is sharing wpid `4055` with `Wireless Mouse M185 old`.

When I try to execute any of solaar command, I got this error:

> solaar: assertion failed: /home/dev/github/Solaar/lib/logitech_receiver/descriptors.py line 85

> solaar: error: duplicate wpid in device descriptors: _DeviceDescriptor(name=u'Wireless Mouse M185 old', kind=NamedInt(2, 'mouse'), wpid=u'4055', codename=u'M185o', protocol=4.5, registers=None, settings=[<Setting([feature:toggle] smooth-scroll)>, <Setting([feature:range] pointer_speed)>])

Not sure what I can do to help, temporarily, I just revised wpid of `Wireless Mouse M185 old`, as I have `Wireless Mouse M235` but I don't have `Wireless Mouse M185 old`, this is a working workaround for me. 

Ref:  #333 #337 #486 #498

**Comment by Lekensteyn** [comment]
The other mouse is located at docs/devices/m185_old.txt
It does not explicitly list a model name, maybe that M185_old entry could be removed from descriptors.py?
Can you also submit a PR that includes the `solaar show` output for your device for future reference?
